version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - leo-net
    command: redis-server --save 60 1 --loglevel warning

  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: leo
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: leo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - leo-net

  adminer:
    image: adminer
    ports: 
      - "8080:8080"
    networks: 
      - leo-net
    
  redisinsight:
    image: redis/redisinsight:latest
    ports: 
      - "5540:5540"
    networks: 
      - leo-net
    
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Web UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks: 
      - leo-net
      
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"

volumes:
  pgdata:

networks:
  leo-net:
    driver: bridge
